export type ClimateProfile = { id: string; name: string; location: string; climateType: string; ambientTemperature: number; solarRadiation: number; sunshineDuration: number; windSpeed: number; relativeHumidity: number }
export type Material = { id: string; name: string; category: 'wall'|'roof'|'floor'|'window'|'door'|'thermal_storage'; thermalConductivity: number; density: number; specificHeat: number; defaultThickness: number; thermalResistance: number; description: string }
export type ShelterDesign = { id: string; name: string; length: number; width: number; height: number; shape: 'Rectangular'|'Square'; orientation: 'North'|'South'|'East'|'West'; windowAreaPercentage: number; doorArea: number; numberOfWindows: number; wallMaterialId: string; roofMaterialId: string; floorMaterialId: string; windowMaterialId: string; doorMaterialId: string; thermalStorageMaterialId: string; climateProfileId: string }
export type SimulationPoint = { timestamp: string; ambientTemperature: number; solarRadiation: number; internalTemperature: number; solarGain: number; heatLoss: number; heatingRequirement: number }
export type SimulationOutput = { points: SimulationPoint[]; averageInternalTemperature: number; totalSolarGain: number; totalHeatLoss: number; totalHeatingRequirement: number; breakdown: { name: string; value: number; color: string }[] }
export type OptimizationResult = { score: number; orientation: ShelterDesign['orientation']; wall: string; roof: string; windowArea: number; thermalStorage: string; solarGain: number; heatLoss: number; heatingRequirement: number; explanation: string[] }

export const climates: ClimateProfile[] = [{ id:'ladakh', name:'Ladakh', location:'Leh, Ladakh', climateType:'Cold & Arid', ambientTemperature:4.8, solarRadiation:612, sunshineDuration:8.7, windSpeed:3.2, relativeHumidity:34 }, { id:'jaipur', name:'Jaipur', location:'Jaipur, Rajasthan', climateType:'Hot & Dry', ambientTemperature:29.4, solarRadiation:684, sunshineDuration:9.3, windSpeed:2.6, relativeHumidity:38 }, { id:'kochi', name:'Kochi', location:'Kochi, Kerala', climateType:'Warm & Humid', ambientTemperature:28.1, solarRadiation:498, sunshineDuration:6.1, windSpeed:2.1, relativeHumidity:77 }]
export const materials: Material[] = [
{id:'rammed-earth',name:'Rammed Earth',category:'wall',thermalConductivity:0.72,density:1900,specificHeat:880,defaultThickness:300,thermalResistance:0.42,description:'High-mass earthen wall system for thermal moderation.'},
{id:'compressed-earth',name:'Compressed Earth Block',category:'wall',thermalConductivity:0.58,density:1750,specificHeat:900,defaultThickness:250,thermalResistance:0.43,description:'Modular earth block with balanced mass and resistance.'},
{id:'lime-plaster',name:'Lime Plaster',category:'wall',thermalConductivity:0.35,density:1400,specificHeat:840,defaultThickness:100,thermalResistance:0.29,description:'Breathable finish layer shown for prototype comparison.'},
{id:'insulated-metal',name:'Insulated Metal Panel',category:'roof',thermalConductivity:0.035,density:120,specificHeat:900,defaultThickness:120,thermalResistance:3.43,description:'Lightweight roof assembly with a high insulation value.'},
{id:'mud-roof',name:'Mud + Lime Roof',category:'roof',thermalConductivity:0.48,density:1500,specificHeat:950,defaultThickness:180,thermalResistance:0.38,description:'High-mass roof concept for passive thermal lag.'},
{id:'stone-slab',name:'Local Stone Slab',category:'floor',thermalConductivity:1.7,density:2300,specificHeat:790,defaultThickness:150,thermalResistance:0.09,description:'Durable floor finish with high thermal mass.'},
{id:'adobe-floor',name:'Adobe Floor',category:'floor',thermalConductivity:0.55,density:1600,specificHeat:1000,defaultThickness:200,thermalResistance:0.36,description:'Earthen floor concept with moderate resistance.'},
{id:'double-glazed',name:'Double Glazed Low-E',category:'window',thermalConductivity:0.8,density:2500,specificHeat:750,defaultThickness:24,thermalResistance:0.31,description:'Window placeholder for lower conductive loss.'},
{id:'timber-door',name:'Insulated Timber Door',category:'door',thermalConductivity:0.14,density:550,specificHeat:1600,defaultThickness:45,thermalResistance:0.32,description:'Door assembly placeholder for prototype calculations.'},
{id:'stone-mass',name:'Stone Thermal Mass',category:'thermal_storage',thermalConductivity:2.2,density:2600,specificHeat:880,defaultThickness:250,thermalResistance:0.11,description:'Dense thermal storage material for temperature retention.'},
]
export const defaultDesign: ShelterDesign = { id:'design-01', name:'Ladakh Passive Study', length:6, width:4.5, height:3, shape:'Rectangular', orientation:'South', windowAreaPercentage:12, doorArea:2.1, numberOfWindows:3, wallMaterialId:'rammed-earth', roofMaterialId:'insulated-metal', floorMaterialId:'stone-slab', windowMaterialId:'double-glazed', doorMaterialId:'timber-door', thermalStorageMaterialId:'stone-mass', climateProfileId:'ladakh' }
export function simulateShelter(design: ShelterDesign, climate: ClimateProfile): SimulationOutput { const points = Array.from({length:24},(_,i)=>{ const hour=i; const solar=Math.max(0, Math.sin((hour-6)/12*Math.PI))*climate.solarRadiation; const wave=Math.sin((hour-7)/24*Math.PI*2); const internal=climate.ambientTemperature+8+solar/110+wave*1.8-(design.windowAreaPercentage-10)*0.08; return {timestamp:`${String(hour).padStart(2,'0')}:00`,ambientTemperature:+(climate.ambientTemperature+wave*3).toFixed(1),solarRadiation:Math.round(solar),internalTemperature:+internal.toFixed(1),solarGain:+(solar*design.windowAreaPercentage/100*0.62).toFixed(0),heatLoss:+(Math.max(0,internal-climate.ambientTemperature)*7.4).toFixed(0),heatingRequirement:+(Math.max(0,18-internal)*3.1).toFixed(0)} }); const avg=points.reduce((a,p)=>a+p.internalTemperature,0)/24; return {points,averageInternalTemperature:+avg.toFixed(1),totalSolarGain:points.reduce((a,p)=>a+p.solarGain,0),totalHeatLoss:points.reduce((a,p)=>a+p.heatLoss,0),totalHeatingRequirement:points.reduce((a,p)=>a+p.heatingRequirement,0),breakdown:[{name:'Walls',value:31,color:'#315a72'},{name:'Roof',value:22,color:'#d9983e'},{name:'Windows',value:18,color:'#5e8fa8'},{name:'Door',value:9,color:'#8c6b4f'},{name:'Floor',value:12,color:'#7a8792'},{name:'Infiltration',value:8,color:'#b9c4ca'}]} }
export function optimizeShelter(_: unknown, climate: ClimateProfile): OptimizationResult { const cold=climate.ambientTemperature<15; return {score:92,orientation:cold?'South':'North',wall:cold?'Rammed Earth':'Compressed Earth Block',roof:cold?'Insulated Metal Panel':'Mud + Lime Roof',windowArea:cold?14:8,thermalStorage:'Stone Thermal Mass',solarGain:cold?4860:3440,heatLoss:cold?2180:2810,heatingRequirement:cold?1260:0,explanation:['Lower predicted heat loss for the selected climate','Higher useful solar gain during occupied hours','Better predicted temperature retention from thermal mass','Lower predicted external heating requirement']} }
export function materialById(id:string){return materials.find(m=>m.id===id) ?? materials[0]}
export function climateById(id:string){return climates.find(c=>c.id===id) ?? climates[0]}
